//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMVCdemo2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class tProduct
    {
        public int fId { get; set; }

        [Required(ErrorMessage ="產品名稱是必填欄位，不可空白")]
        [DisplayName("產品名稱")]
        public string fName { get; set; }

        [DisplayName("庫存量")]
        public Nullable<int> fQty { get; set; }

        [DisplayName("成本")]
        public Nullable<decimal> fCost { get; set; }

        [DisplayName("價格")]
        public Nullable<decimal> fPrice { get; set; }

        [DisplayName("圖片路徑")]
        public string fImagePath { get; set; }
        public HttpPostedFileBase photo { get; set; }
    }
}
